WildSteak/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("menu.urls"))
]

menu/urls.py
from django.urls import path, include
from .import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutPage, name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("menu", views.MenuItemList.as_view(), name="menu"),
    path("menu/create", views.MenuItemCreate.as_view(), name="new_item"),
    path("inventory", views.IngredientList.as_view(), name="inventory"),
    path("inventory/create", views.IngredientCreate.as_view(), name="new_ingredient"),
    path("inventory/update/<pk>", views.IngredientUpdate.as_view(), name="ingredient_update"),
    path("inventory/delete/<pk>", views.IngredientDelete.as_view(), name="ingredient_delete"),
    path("purchases", views.PurchaseView.as_view(), name="purchases"),
    path("purchases/create", views.PurchaseCreate, name="new_purchase"),
    path("recipe", views.RecipeList.as_view(), name="recipe"),
    path("recipe/create", views.RecipeCreate.as_view(), name="new_recipe"),
]

menu/models.py
from django.db import models

# Create your models here.
class MenuItem(models.Model):
    title = models.CharField(max_length=200)
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/menu"

class Ingredient(models.Model):
    UNITS = [
        ("gram", "g"),
        ("kilogram", "kg"),
        ("piece", "pcs"),
        ("mililitr", "ml"),
        ("litre", "l"),
        ("other", "other")
    ]
    name = models.CharField(max_length=200)
    quantity = models.FloatField(null=True)
    unit = models.CharField(max_length=10, choices=UNITS, default="other")
    unit_price = models.FloatField(null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/inventory"

class RecipeRequirements(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField()

    def get_absolute_url(self):
        return "/recipe"

class Purchase(models.Model):
    menu_item = models.ForeignKey(MenuItem, related_name="menuitem", on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return "/purchases"

    def __str__(self):
        return self.menu_item.title

menu/forms.py
from django import forms
from .models import Purchase
from django.contrib.auth.models import User

class PurchaseCreateForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'

#class CreationForm(forms.ModelForm):
#    class Meta:
#        model = User

menu/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .models import MenuItem, Ingredient, RecipeRequirements, Purchase
from .forms import PurchaseCreateForm


# Create your views here.
class SignUp(CreateView):
    template_name = "menu/registration/signup.html"
    success_url = reverse_lazy("login")
    form_class = UserCreationForm

#1st user
#username="Pablo", email="pablo@wildesteak.com", password="steak123"

def loginPage(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        #try:
        #    user = User.objects.get(username=username)
        #except:
        #    messages.error(request, "User does not exist")

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            messages.error(request, "Username or password does not exist")
    context = {}
    return render(request, "menu/registration/login.html")

def logoutPage(request):
    logout(request)
    return redirect('home')


def home(request):
    return render(request, "menu/home.html")

class MenuItemList(ListView):
    template = "menu/menuitem_list.html"
    model = MenuItem


class MenuItemCreate(LoginRequiredMixin, CreateView):
    model = MenuItem
    template_name = "menu/menuitem_create_form.html"
    fields = ["title", "price"]
    login_url = "login"

class IngredientList(ListView):
    template_name = "menu/ingredient_list.html"
    model = Ingredient


class IngredientCreate(LoginRequiredMixin, CreateView):
    template_name = "menu/ingredient_create_form.html"
    model = Ingredient
    fields = ["name", "quantity", "unit", "unit_price"]
    login_url = "login"

class IngredientDelete(LoginRequiredMixin, DeleteView):
    template_name = "menu/ingredient_delete_form.html"
    model = Ingredient
    login_url = "login"

class IngredientUpdate(LoginRequiredMixin, UpdateView):
    template_name = "menu/ingredient_update_form.html"
    model = Ingredient
    fields = ["name", "quantity", "unit", "unit_price"]
    login_url = "login"

class RecipeList(ListView):
    template_name = "menu/recipe_list.html"
    model = RecipeRequirements

class RecipeCreate(LoginRequiredMixin, CreateView):
    template_name = "menu/recipe_create_form.html"
    model = RecipeRequirements
    fields = ["menu_item", "ingredient", "quantity"]
    login_url = "login"

class PurchaseView(ListView):
    template_name = "menu/purchases_list.html"
    model = Purchase
    #function to use to get context ot be used
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        purchases = Purchase.objects.all()
        sum = 0
        total_cost = 0
        # recipe.quantity * ingredient.unit_price

        for purchase in purchases:
            sum += purchase.menu_item.price
            recipes = RecipeRequirements.objects.filter(menu_item=purchase.menu_item)
            for recipe in recipes:
                ingred = Ingredient.objects.get(id=recipe.ingredient.id)
                total_cost += recipe.quantity * ingred.unit_price
        profit = sum - total_cost
        data['sum'] = sum
        data['total_cost'] = total_cost
        data['profit'] = profit
        return data

@login_required(login_url="login")
def PurchaseCreate(request):
    form = PurchaseCreateForm()
    context = {"form": form}
    if request.method == "POST":
        form = PurchaseCreateForm(request.POST)
        if form.is_valid():
            purchase = form.save()
            #Line that gives recipe objects
            recipe = RecipeRequirements.objects.filter(menu_item=request.POST.get("menu_item"))
            #extracting quantiyty needed to be subtracted from inventory numbers
            for elem in recipe:
                ingr = Ingredient.objects.get(id=elem.ingredient.id)
                if ingr.quantity > elem.quantity:
                    ingr.quantity = ingr.quantity - elem.quantity
                    ingr.save()
            return redirect('purchases')

    return render(request, "menu/purchase_create_form.html", context)

menu/templates/menu/base.html
<body>
{% include 'menu/navbar.html' %}
{% load static %}

{% block head %}
<link href ="{% static 'menu/style.css' %}" rel="stylesheet">
{% endblock %}




{% block content %}
{% endblock %}
</body>

menu/templates/menu/home.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Home</h1>
<div class='description'>
    <h3>Example of a webpage focused on basic backend functionality.</h3>
    <ul>
       <li>Database for Menu, Inventory, Purchase, Recipes</li>
       <li>CRUD functionality</li>
       <li>Dynamically updated Cost/Profit/Revenue</li>
       <li>Inventory updated with each purchase based on recipe requirements</li>
       <li>Login/Logout, Entries restricted to logged users</li>
    </ul>
</div>
{% endblock %}

menu/templates/menu/ingredient_create_form.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Add ingredient</h1>
<form method="post">
    <div>
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Submit" />
    </div>
</form>
{% endblock %}

menu/templates/menu/ingredient_delete_form.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Delete ingredient</h1>
<form action="" method="POST">
    <div>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Confirm"/>
    </div>
</form>
{% endblock %}

menu/templates/menu/ingredient_list.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Inventory</h1>
<a href="{% url 'new_ingredient' %}"><button class="btn">Add new ingredient</button></a>

<table class="inventory">
    <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Price</th>

    </tr>
    <tr>
        {% for item in ingredient_list %}
    </tr>
    <tr>
        <td>{{ item.name }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.unit }}</td>
        <td>{{ item.unit_price }}</td>
        <td><a href="{% url 'ingredient_update' item.id %}">Edit</a></td>
        <td><a href="{% url 'ingredient_delete' item.id %}">Delete</a></td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

menu/templates/menu/ingredient_update_form.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Update inventory</h1>
<form method="post">
    <div>
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Submit" />
    </div>
</form>
{% endblock %}

menu/templates/menu/menuitem_create_form.html
{% extends 'menu/base.html' %}
{% block content %}
<h1>Add menu item</h1>
<form method="post">
    <div>
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Submit" />
    </div>
</form>
{% endblock %}

menu/templates/menu/menuitem_list.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Menu</h1>
<a href="{% url 'new_item' %}"><button class="btn">Add menu item</button></a>
<table class="menu">
    <tr>
        <th>Dish</th>
        <th>Price</th>
    </tr>
    <tr>
        {% for item in menuitem_list %}
    </tr>
    <tr>
        <td>{{ item.title }}</td>
        <td>{{ item.price }}</td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

menu/templates/menu/navbar.html
{% load static %}
<link href ="{% static 'menu/style.css' %}" rel="stylesheet">
    <div class="navbar">
    <ul>
        <li><a href="{% url 'home'%}">Home</a></li>
        <li><a href="{% url 'menu' %}">Menu</a></li>
        <li><a href="{% url 'inventory' %}">Inventory</a></li>
        <li><a href="{% url 'purchases' %}">Purchases</a></li>
        <li><a href="{% url 'recipe' %}">Recipes</a></li>
        <li><a href="{% url 'login' %}">Login</a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'logout' %}">Logout</a></li>
        <li><a> Logged as: {{ request.user }}</a></li>
    </ul>
        {% endif %}
    </div>

menu/templates/menu/purchase_create_form.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Register purchase</h1>
<form method="post">
    <div>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </div>
</form>
{% endblock %}

menu/templates/menu/purchases_list.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Purchases</h1>
<h3>Total revenue:  {{ sum }}       </h3>
<h3>Total cost:     {{ total_cost|floatformat:2 }}</h3>
<h3>Profit:         {{ profit|floatformat:2 }}    </h3>
<a href="{% url 'new_purchase' %}"><button class="btn">Register purchase</button></a>
<table class="purchases">
    <tr>
        <th>Dish</th>
        <th>Purchase time</th>

    </tr>
    <tr>
        {% for item in purchase_list %}
    </tr>
    <tr>
        <td>{{ item.menu_item }}</td>
        <td>{{ item.date }}</td>
        {% endfor %}

    </tr>


</table>
{% endblock %}

menu/templates/menu/recipe_create_form.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Add recipe</h1>
<form method="post">
    <div>
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </div>
</form>
{% endblock %}

menu/templates/menu/recipe_list.html
{% extends 'menu/base.html' %}

{% block content %}
<h1>Recipes</h1>
<a href="{% url 'new_recipe' %}"><button class="btn">Add new recipe</button></a>
<table class="recipes">
    <tr>
        <th>Dish</th>
        <th>Ingredient</th>
        <th>Amount</th>
    </tr>
    <tr>
        {% for item in reciperequirements_list %}
    </tr>
    <tr>
        <td> {{ item.menu_item }} </td>
        <td> {{ item.ingredient }} </td>
        <td> {{ item.quantity }} </td>
        {% endfor %}
    </tr>
</table>
{% endblock %}